import CryptoKit
import Foundation

/// クリップボード取り込みの判定ロジック（純粋関数のみ・テスト対象）
public enum CaptureRules {
    public static let plainTextType = "public.utf8-plain-text"
    public static let storedTextTypes = ["public.utf8-plain-text", "public.rtf", "public.html"]
    /// 画像の保存形式。取り込み時に TIFF もこれへ変換して 1 本化する
    public static let pngType = "public.png"
    public static let imageTypes = [pngType, "public.tiff"]

    /// パスワードマネージャー等が付与する「履歴に残すべきでない」マーカー
    public static let skipMarkerTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public static let maxItemBytes = 50 * 1024 * 1024
    public static let previewMaxLength = 400
    /// 検索で見る本文の上限。preview より長く取るが、巨大なコピー 1 件で
    /// インデックス（items.json）が膨らまないよう頭で切る
    public static let searchTextMaxLength = 2000
    public static let maxItems = 500

    public static func shouldSkip(types: [String]) -> Bool {
        types.contains { skipMarkerTypes.contains($0) }
    }

    /// 取り込むべき種別を判定する。nil なら取り込み対象なし
    public static func detectKind(text: String?, hasImage: Bool, fileURLCount: Int) -> ItemKind? {
        if fileURLCount > 0 { return .fileList }
        let trimmed = text?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if !trimmed.isEmpty { return isSingleURL(trimmed) ? .link : .text }
        if hasImage { return .image }
        return nil
    }

    public static func isSingleURL(_ text: String) -> Bool {
        guard !text.contains(where: { $0.isWhitespace || $0.isNewline }) else { return false }
        guard let url = URL(string: text), let scheme = url.scheme?.lowercased() else { return false }
        return ["http", "https"].contains(scheme) && url.host != nil
    }

    public static func makePreview(_ text: String) -> String {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > previewMaxLength else { return trimmed }
        return String(trimmed.prefix(previewMaxLength)) + "…"
    }

    /// 検索用に持っておく本文。preview に収まりきらなかったときだけ返す。
    ///
    /// カードに出す preview は先頭 400 文字で切れるため、それだけを検索していると
    /// 長いメール本文の後半にある語では見つけられない。かといって全文を
    /// インデックスへ入れると、短いコピーばかりの履歴でも同じ文字列を二重に持つことになる。
    /// preview で足りるものは nil にして、足りないものだけ長い方を持つ
    public static func searchText(_ text: String) -> String? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > previewMaxLength else { return nil }
        return String(trimmed.prefix(searchTextMaxLength))
    }

    public static func contentHash(flavors: [String: Data], fileURLs: [String]) -> String {
        var hasher = SHA256()
        for key in flavors.keys.sorted() {
            hasher.update(data: Data(key.utf8))
            hasher.update(data: flavors[key] ?? Data())
        }
        for url in fileURLs {
            hasher.update(data: Data(url.utf8))
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}
